import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
	plugins: [sveltekit()],
	build: {
		rollupOptions: {
			// pagefind bundle is generated by the postbuild step; externalize at build time
			external: ['/pagefind/pagefind.js'],
		},
	},
	define: {
		__CONTENT_ROOT__: JSON.stringify(path.resolve(__dirname, 'content')),
	},
});
